flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- Ranged-sets-0.3.0
- canteven-log-1.0.0.0
- data-bword-0.1.0.1
- data-dword-0.3.1
- legion-0.1.0.0
- scotty-resource-0.1.1.0
resolver: lts-6.13
